### ISSUE TITLE
Difficulty in installing the add-in in ArcGIS Pro.

### ISSUE THREAD

**Issue by Yogesh-Chavan** [nicogis/ArcGISPro_AddIn_ChatGPT#1]
Hi Nico,

Hope you are doing well.

Can you kindly add more details/steps on how or which file to use to get the add-in in ArcGIS Pro, the downloadable does not have the add-in file we can install directly.

It would be great if you can share a short video on this.

This is really great. Hence thought of connecting with you.

**Comment by nicogis** [comment]
You can download last version (file PAMChatGPT.esriAddinX) [here](https://github.com/nicogis/ArcGISPro_AddIn_ChatGPT/releases/tag/v1.1.0)

To install add-ins ArcGIS Pro [link ](https://pro.arcgis.com/en/pro-app/latest/get-started/manage-add-ins.htm)

Now in readme you can see a short video
